sources:
  - name: GatewaySDK
    handler:
      graphql:
        endpoint: '$GRAPHQL_ENDPOINT'
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - Query.!transaction
            - Query.!transactions

customFetch: ./custom-fetch.ts

sdk:
  generateOperations:
    selectionSetDepth: 2
