sources:
  - name: MyGraphQLApi
    handler:
      graphql:
        endpoint: https://develop.protocol.mygateway.xyz/v1/graphql
        method: 'POST'
        useGETForQueries: false
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - Query.!transaction
            - Query.!transactions

customFetch: ./custom-fetch.ts

sdk:
  generateOperations:
    selectionSetDepth: 2
