sources:
  - name: GatewaySDK
    handler:
      graphql:
        endpoint: https://develop.protocol.mygateway.xyz/graphql
    transforms:
      - rename:
          mode: bare
          renames:
            - from:
                type: PDAMetadata
                field: status
              to:
                type: PDAMetadata
                field: pdametadastatus

customFetch: ./custom-fetch.js

sdk:
  generateOperations:
    selectionSetDepth: 2
