sources:
  - name: MyGraphQLApi
    handler:
      graphql:
        endpoint: https://develop.protocol.mygateway.xyz/v1/graphql
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - Query.!transaction
            - Query.!transactions
            - Query.!myTransactions
customFetch: ./custom-fetch.ts

sdk:
  generateOperations:
    selectionSetDepth: 2
