sources:
  - name: GatewaySDK
    handler:
      graphql:
        endpoint: https://develop.protocol.mygateway.xyz/graphql
    transforms:
      - filterSchema:
          mode: bare
          filters:
            - PDAMetadata.!status

customFetch: ./custom-fetch.js

sdk:
  generateOperations:
    selectionSetDepth: 2
