import {
  Activity,
  ActivityAction,
  Role,
} from '../../gatewaySdk/sources/Gateway';

export const activityStub = (overrideActivity?: Activity) => ({
  action: 'USER_CREATE' as ActivityAction,
  createdAt: '2024-06-25T12:02:34.587Z',
  id: '667ab1dac4d49d302a576fb7',
  metadata: {
    creator: '',
    dataModel: '',
    dataModelString: '',
    issuer: '',
    organization: '',
    owner: '',
    pda: 1,
    pdas: [1],
    proof: '',
    signedBy: '',
    status: '',
    user: '',
    users: [''],
  },
  read: true,
  signature: null,
  source: {
    did: 'did:gatewayid:238',
    roles: ['User'] as Role[],
    username: 'sid_desktop',
    createdAt: '2024-06-25T12:02:41.828Z',
    description: 'dsfds',
    encryptionKey: 'dsfdsfads',
    id: 'dsfdsfdsfdsf',
    issuedPDAs: [],
    usernameLastUpdated: '2024-06-25T12:02:41.828Z',
    name: 'dos',
    receivedPDAs: [],
    recipientDataRequests: [],
    totalFileSize: 21312321,
    updatedAt: '2024-06-25T12:02:41.828Z',
    verifierDataRequests: [],
    receivedProofs: [],
  },
  target: null,
  updatedAt: '2024-06-25T12:02:41.828Z',
  ...overrideActivity,
});
