import {
  FilterDataModelInput,
  myActivitiesCountQueryQueryVariables,
  myActivitiesQueryQueryVariables,
  myPDACountQueryQueryVariables,
  myPDAsQueryQueryVariables,
  Sdk,
  UpdateUserInput,
  UserIdentifierType,
} from '../../../gatewaySdk/sources/Gateway';
import { errorHandler } from '../../helpers/helper';
import { ValidationService } from '../../services/validator-service';

export class User {
  private sdk: Sdk;
  private validationService: ValidationService;

  constructor(sdk: Sdk, validationService: ValidationService) {
    this.sdk = sdk;
    this.validationService = validationService;
  }

  /**
   * The function `me` makes an asynchronous call to `me_query` and returns the result, or throws an
   * error if something goes wrong.
   * @returns a Promise that resolves to me.
   */
  async me() {
    try {
      return await this.sdk.meQuery();
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * The function takes a user identifier type and value as input, queries the user using the SDK, and
   * returns the result.
   * @param  - - `type`: The type of user identifier. It can be one of the following values:
   * @returns The `user` function is returning the result of the `user_query` method call from the `sdk`
   * object.
   */
  async getSingleUser({
    type,
    value,
  }: {
    type: UserIdentifierType;
    value: string;
  }) {
    try {
      this.validationService.validateString(value);
      return await this.sdk.userQuery({ input: { type, value } });
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * The function `myPDACount` is an asynchronous function that returns the count of a user's PDA
   *  based on an optional filter.
   * @param {myPDACountQueryQueryVariables} [filter] - The `filter` parameter is an optional input that allows you to
   * specify criteria for filtering the PDAs before counting them. It is
   * of type `FilterPDAInput`.
   * @returns a Promise that resolves to a number.
   */
  async myPDACount(filter?: myPDACountQueryQueryVariables) {
    try {
      if (filter?.filter) {
        this.validationService.validatePDAFilter(filter.filter);
      }
      return (await this.sdk.myPDACountQuery(filter)).myPDACount;
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * The function `myPDAs` is an asynchronous function that takes in a `myPDAs_queryQueryVariables` object and returns a
   * promise that resolves to a `myPDAs_queryQuery` object.
   * @param {myPDAsQueryQueryVariables}  - - `filter`: An object that contains filter criteria for the query.
   * @returns a Promise that resolves to a value of type `myPDAs_queryQuery`.
   */
  async myPDAs(filter?: myPDAsQueryQueryVariables) {
    try {
      if (filter?.filter) {
        this.validationService.validatePDAFilter(filter.filter);
      }
      return await this.sdk.myPDAsQuery(filter);
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * The function `myDataModelsCount` is an asynchronous function that retrieves the count of data
   * models based on an optional filter and returns the count.
   * @param {FilterDataModelInput} [filter] - The `filter` parameter is an optional input that allows
   * you to specify conditions to filter the data models. It is of type `FilterDataModelInput`. You can
   * use this parameter to define criteria such as filtering by a specific field value or applying
   * logical operators like AND and OR to combine multiple conditions.
   * @returns the count of data models that match the provided filter.
   */
  async myDataModelsCount(filter?: FilterDataModelInput) {
    try {
      return (await this.sdk.dataModelsCountQuery({ filter })).dataModelsCount;
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * This TypeScript function asynchronously fetches activities based on a given filter and handles any
   * errors that occur.
   * @param {myActivitiesQueryQueryVariables} [filter] - The `filter` parameter in the `myActivities`
   * function is of type `myActivitiesQueryQueryVariables`. This parameter is used to pass any
   * filtering criteria or variables needed for the `myActivitiesQuery` function call.
   * @returns The `myActivities` function is returning the result of the `myActivitiesQuery` function
   * from the SDK after applying the provided `filter`. If an error occurs during the query execution,
   * it will be caught and rethrown with an error message generated by the `errorHandler` function.
   */
  async myActivities(filter?: myActivitiesQueryQueryVariables) {
    try {
      return await this.sdk.myActivitiesQuery(filter);
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * This TypeScript function asynchronously retrieves the count of a user's activities based on the
   * provided filter.
   * @param {myActivitiesCountQueryQueryVariables} [filter] - The `filter` parameter in the
   * `myActivitiesCount` function is of type `myActivitiesCountQueryQueryVariables`. This parameter is
   * used to filter the activities for which you want to count the total number.
   * @returns The `myActivitiesCount` function is returning the count of activities based on the
   * provided filter, which is obtained by calling the `myActivitiesCountQuery` function from the SDK.
   */
  async myActivitiesCount(filter?: myActivitiesCountQueryQueryVariables) {
    try {
      return (await this.sdk.myActivitiesCountQuery(filter)).myActivitiesCount;
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }

  /**
   * The function `updateMe` asynchronously updates the user's information using the provided input.
   * @param {UpdateUserInput} updatedBody - The `updatedBody` parameter in the `updateMe` function is
   * of type `UpdateUserInput`. This parameter likely contains the updated information for a user that
   * needs to be passed to the `updateMyUserMutation` method of the SDK for updating the user's data.
   * @returns The `updateMe` function is returning the result of the `updateMyUserMutation` call with
   * the `updatedBody` input.
   */
  async updateMe(updatedBody: UpdateUserInput) {
    try {
      return await this.sdk.updateMyUserMutation({ input: updatedBody });
    } catch (error) {
      throw new Error(errorHandler(error));
    }
  }
}
