export const routes = {
  CreateAccount: '/accounts',
  GetMyAccount: '/accounts/me',
  UpdateAccount: '/accounts/me',
  AddWallet: '/accounts/me/wallets',
  RemoveWallet: '/accounts/me/wallets/{address}',
  AuthenticateAccount: '/auth',
  GenerateSignMessage: '/auth/message',
  RefreshToken: '/auth/refresh-token',
  CreateANewDataAsset: '/data-assets',
  GetCreatedDataAssets: '/data-assets/created',
  GetReceivedDataAssets: '/data-assets/received',
  GetDataAssetByID: '/data-assets/{id}',
  UpdateDataAssetByID: '/data-assets/{id}',
  DeleteDataAssetByID: '/data-assets/{id}',
  AssignACLItemsToDataAsset: '/data-assets/{id}/acl',
  UpdateACLItemsToDataAsset: '/data-assets/{id}/acl',
  DeleteAssignedRoleByACL: '/data-assets/{id}/acl/delete',
  DownloadDataAssetByID: '/data-assets/{id}/download',
  ShareDataAssetByID: '/data-assets/{id}/share',
  GetDataModels: '/data-models',
  CreateDataModel: '/data-models',
  GetDataModelsByUser: '/data-models/me',
  GetDataModelByID: '/data-models/{id}',
  UpdateDataModel: '/data-models/{id}',
};
