export const routes = {
  CreateAccount: '/accounts',
  GetMyAccount: '/accounts/me',
  UpdateAccount: '/accounts/me',
  AuthenticateAccount: '/auth',
  GenerateSignMessage: '/auth/message',
  RefreshToken: '/auth/refresh-token',
  CreateANewDataAsset: '/data-assets',
  GetMyDataAssets: '/data-assets/me',
  GetDataAssetByID: '/data-assets/{id}',
  UpdateDataAssetByID: '/data-assets/{id}',
  DeleteDataAssetByID: '/data-assets/{id}',
  UpdateACLItemsToDataAsset: '/data-assets/{id}/acl',
  AssignACLItemsToDataAsset: '/data-assets/{id}/acl',
  DeleteAssignedRoleByACL: '/data-assets/{id}/acl',
  DownloadDataAssetByID: '/data-assets/{id}/download',
  ShareDataAssetByID: '/data-assets/{id}/share',
  GetDataModels: '/data-models',
  CreateDataModel: '/data-models',
  GetDataModelsByUser: '/data-models/me',
  GetDataModelByID: '/data-models/{id}',
  UpdateDataModel: '/data-models/{id}',
};
